config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  root 'pages#home'

  resources :aeronaves
  resources :alunos

end

app/models/aeronafe.rb
class Aeronafe < ActiveRecord::Base

validates_presence_of :nome, on: :create, message: " não pode ficar em branco"
validates_presence_of :numeroTripulantes, on: :create, message: " não pode ficar em branco"
validates_presence_of :tamanho, on: :create, message: " não pode ficar em branco"
validates_presence_of :numero, on: :create, message: " não pode ficar em branco"
validates_presence_of :chassi, on: :create, message: " não pode ficar em branco"
validates_presence_of :quantidadeHorasVoo, on: :create, message: " não pode ficar em branco"
validates_presence_of :quantidadeMotor, on: :create, message: " não pode ficar em branco"
end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
validates_presence_of :nome, on: :create, message: " não pode ficar em branco"
validates_presence_of :sobrenome, on: :create, message: " não pode ficar em branco"
validates_presence_of :cpf, on: :create, message: " não pode ficar em branco"
validates_presence_of :endereco, on: :create, message: " não pode ficar em branco"
validates_presence_of :profissao, on: :create, message: " não pode ficar em branco"
validates_presence_of :email, on: :create, message: " não pode ficar em branco"
validates_presence_of :cnh, on: :create, message: " não pode ficar em branco"
validates_presence_of :escolaridade, on: :create, message: " não pode ficar em branco"
validates_presence_of :instituicao, on: :create, message: " não pode ficar em branco"
validates_presence_of :curso, on: :create, message: " não pode ficar em branco"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/aeronaves_controller.rb
class AeronavesController < ApplicationController
  before_action :set_aeronafe, only: [:show, :edit, :update, :destroy]
  
  before_action:authenticate_user!

  # GET /aeronaves
  # GET /aeronaves.json
  def index
    @aeronaves = Aeronafe.all
  end

  # GET /aeronaves/1
  # GET /aeronaves/1.json
  def show
  end

  # GET /aeronaves/new
  def new
    @aeronafe = Aeronafe.new
  end

  # GET /aeronaves/1/edit
  def edit
  end

  # POST /aeronaves
  # POST /aeronaves.json
  def create
    @aeronafe = Aeronafe.new(aeronafe_params)

    respond_to do |format|
      if @aeronafe.save
        format.html { redirect_to @aeronafe, notice: 'Aeronafe was successfully created.' }
        format.json { render :show, status: :created, location: @aeronafe }
      else
        format.html { render :new }
        format.json { render json: @aeronafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aeronaves/1
  # PATCH/PUT /aeronaves/1.json
  def update
    respond_to do |format|
      if @aeronafe.update(aeronafe_params)
        format.html { redirect_to @aeronafe, notice: 'Aeronafe was successfully updated.' }
        format.json { render :show, status: :ok, location: @aeronafe }
      else
        format.html { render :edit }
        format.json { render json: @aeronafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aeronaves/1
  # DELETE /aeronaves/1.json
  def destroy
    @aeronafe.destroy
    respond_to do |format|
      format.html { redirect_to aeronaves_url, notice: 'Aeronafe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aeronafe
      @aeronafe = Aeronafe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aeronafe_params
      params.require(:aeronafe).permit(:nome, :numeroTripulantes, :tamanho, :numero, :chassi, :quantidadeHorasVoo, :quantidadeMotor)
    end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]
  
  before_action:authenticate_user!

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :sobrenome, :cpf, :endereco, :profissao, :email, :cnh, :escolaridade, :instituicao, :curso)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/aeronaves_helper.rb
module AeronavesHelper
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/aeronaves/_form.html.erb
<%= form_for(@aeronafe) do |f| %>
  <% if @aeronafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aeronafe.errors.count, "error") %> prohibited this aeronafe from being saved:</h2>

      <ul>
      <% @aeronafe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :numeroTripulantes %><br>
    <%= f.text_field :numeroTripulantes %>
  </div>
  <div class="field">
    <%= f.label :tamanho %><br>
    <%= f.text_field :tamanho %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :chassi %><br>
    <%= f.text_field :chassi %>
  </div>
  <div class="field">
    <%= f.label :quantidadeHorasVoo %><br>
    <%= f.text_field :quantidadeHorasVoo %>
  </div>
  <div class="field">
    <%= f.label :quantidadeMotor %><br>
    <%= f.text_field :quantidadeMotor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aeronaves/edit.html.erb
<h1>Editing Aeronafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @aeronafe %> |
<%= link_to 'Back', aeronaves_path %>

app/views/aeronaves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Aeronaves</h1>

<table style="width:100%">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Numerotripulantes</th>
      <th>Tamanho</th>
      <th>Numero</th>
      <th>Chassi</th>
      <th>Quantidadehorasvoo</th>
      <th>Quantidademotor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aeronaves.each do |aeronafe| %>
      <tr>
        <td><%= aeronafe.nome %></td>
        <td><%= aeronafe.numeroTripulantes %></td>
        <td><%= aeronafe.tamanho %></td>
        <td><%= aeronafe.numero %></td>
        <td><%= aeronafe.chassi %></td>
        <td><%= aeronafe.quantidadeHorasVoo %></td>
        <td><%= aeronafe.quantidadeMotor %></td>
        <td><%= link_to 'Show', aeronafe %></td>
        <td><%= link_to 'Edit', edit_aeronafe_path(aeronafe) %></td>
        <td><%= link_to 'Destroy', aeronafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aeronafe', new_aeronafe_path %>

app/views/aeronaves/new.html.erb
<h1>New Aeronafe</h1>

<%= render 'form' %>

<%= link_to 'Back', aeronaves_path %>

app/views/aeronaves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aeronafe.nome %>
</p>

<p>
  <strong>Numerotripulantes:</strong>
  <%= @aeronafe.numeroTripulantes %>
</p>

<p>
  <strong>Tamanho:</strong>
  <%= @aeronafe.tamanho %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @aeronafe.numero %>
</p>

<p>
  <strong>Chassi:</strong>
  <%= @aeronafe.chassi %>
</p>

<p>
  <strong>Quantidadehorasvoo:</strong>
  <%= @aeronafe.quantidadeHorasVoo %>
</p>

<p>
  <strong>Quantidademotor:</strong>
  <%= @aeronafe.quantidadeMotor %>
</p>

<%= link_to 'Edit', edit_aeronafe_path(@aeronafe) %> |
<%= link_to 'Back', aeronaves_path %>

app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sobrenome %><br>
    <%= f.text_field :sobrenome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :profissao %><br>
    <%= f.text_field :profissao %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cnh %><br>
    <%= f.text_field :cnh %>
  </div>
  <div class="field">
    <%= f.label :escolaridade %><br>
    <%= f.text_field :escolaridade %>
  </div>
  <div class="field">
    <%= f.label :instituicao %><br>
    <%= f.text_field :instituicao %>
  </div>
  <div class="field">
    <%= f.label :curso %><br>
    <%= f.text_field :curso %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form' %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Alunos</h1>

<table style="width:100%">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Cpf</th>
      <th>Endereco</th>
      <th>Profissao</th>
      <th>Email</th>
      <th>Cnh</th>
      <th>Escolaridade</th>
      <th>Instituicao</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.sobrenome %></td>
        <td><%= aluno.cpf %></td>
        <td><%= aluno.endereco %></td>
        <td><%= aluno.profissao %></td>
        <td><%= aluno.email %></td>
        <td><%= aluno.cnh %></td>
        <td><%= aluno.escolaridade %></td>
        <td><%= aluno.instituicao %></td>
        <td><%= aluno.curso %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form' %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @aluno.sobrenome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @aluno.cpf %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @aluno.endereco %>
</p>

<p>
  <strong>Profissao:</strong>
  <%= @aluno.profissao %>
</p>

<p>
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

<p>
  <strong>Cnh:</strong>
  <%= @aluno.cnh %>
</p>

<p>
  <strong>Escolaridade:</strong>
  <%= @aluno.escolaridade %>
</p>

<p>
  <strong>Instituicao:</strong>
  <%= @aluno.instituicao %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @aluno.curso %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/pages/home">Aeroclube Asas</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
      
      

        <% if current_user %>
            <li><%= link_to 'Alunos', alunos_path %></li>
            <li><%= link_to 'Aeronaves', aeronaves_path %></li>
            <li><%= link_to 'Editar Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
        <% else %>       
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>

        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AeroclubeAsas2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header'%>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Aeroclube Asas</h1>
<p>Find me in app/views/pages/home.html.erb</p>